---
resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/MarcAssmann/concourse-reporting.git

jobs:
- name: reporting-job
  public: true
  plan:
  - get: scripts
  - task: reporting-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: bobohund/buildtools}
      inputs:
        - name: scripts
      run:
        path: ./scripts/report.sh
        args: [param2]
